/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class StringUtilsTest {
    @Test public void testIsPositiveNumber() {
        StringUtils classUnderTest = new StringUtils();
        assertTrue(classUnderTest.isPositiveNumber("123"));
    }
}
