/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

public class StringUtils {
    public boolean isPositiveNumber(String str) {
        return  org.apache.commons.lang3.StringUtils.isNumeric(str);
    }
}
